db_tools:
    # Where to put generated backups
    # storage_directory: '%kernel.project_dir%/var/private/db_tools'

    # When old backups are considered obsolete
    # (Use relative date/time formats : https://www.php.net/manual/en/datetime.formats.relative.php)
    # backup_expiration_age: '6 months ago' # default '3 months ago'

    # List here tables (per connection) you don't want in your backups
    # excluded_tables:
    #   - default: ['table1', 'table2']

    # Specify here paths to binaries, only if the system can't find them by himself
    # backupper_binaries:
    #     pgsql: 'usr/bin/pg_dump' # default 'pg_dump'
    #     pdo_pgsql: 'usr/bin/pg_dump' # default 'pg_dump'
    #     pdo_mysql: 'usr/bin/mysqldump' # default 'mysqldump'
    # restorer_binaries:
    #     pgsql: 'usr/bin/pg_restore' # default 'pg_restore'
    #     pdo_pgsql: 'usr/bin/pg_restore' # default 'pg_restore'
    #     pdo_mysql: 'usr/bin/mysql' # default 'mysql'

    # Update this configuration if you want to look for anonymizers in a custom folder.
    # These are default paths that will always be registered even if you override the
    # the setting and don't repeat them:
    # anonymizer_paths:
    #     - '%kernel.project_dir%/vendor/makinacorpus/db-tools-bundle/src/Anonymizer'
    #     - '%kernel.project_dir%/src/Anonymizer'

    # Anonymization configuration.
    # anonymization:
    #     # `yaml` or `attributes`, default `attributes`
    #     type: yaml
    #     # give a file only for `yaml`,
    #     # for attributes, the DbToolsBundle will  automaticly look for
    #     # anonymization on Doctrine entities class
    #     file: '%kernel.project_dir%/config/anonymizations.yaml'
