version: '3.8'
services:
    php_fpm:
        build: ./docker/php-fpm
        networks:
            - db-tools-test
        volumes:
            - ./:/var/www
    mysql57:
        image: mysql:5.7
        restart: 'no'
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 9501:3306
        networks:
            - db-tools-test
    mysql80:
        image: mysql:8
        restart: 'no'
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 9502:3306
        networks:
            - db-tools-test
    mariadb11:
        image: mariadb:11
        restart: 'no'
        environment:
            MYSQL_DATABASE: test_db
            MARIADB_ROOT_PASSWORD: password
        ports:
            - 9503:3306
        networks:
            - db-tools-test
    postgresql10:
        image: postgres:10
        restart: 'no'
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 9504:5432
        networks:
            - db-tools-test
    postgresql16:
        image: postgres:16
        restart: 'no'
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 9505:5432
        networks:
            - db-tools-test

networks:
  db-tools-test: